using FluentValidation;
using ResidentialExpenseControl.Core.DomainObjects;
using ResidentialExpenseControl.Domain.Interfaces;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;

namespace ResidentialExpenseControl.Domain.Notifications
{
    /// <summary>
    /// Handles domain notifications.
    /// </summary>
    public class Notifier : INotifier
    {
        private readonly List<Notification> _notifications;

        public Notifier()
        {
            _notifications = new List<Notification>();
        }

        public void Handle(Notification notification)
        {
            _notifications.Add(notification);
        }

        public List<Notification> GetNotifications()
        {
            return _notifications;
        }

        public bool HasNotification()
        {
            return _notifications.Any();
        }

        /// Collection of added notifications
        [JsonIgnore]
        public IReadOnlyCollection<Notification> Notifications => _notifications;

        /// Collection of all messages generated by notifications.
        [JsonIgnore]
        public IReadOnlyCollection<string> Messages => _notifications.Any() ? _notifications.Select(x => x.Message).ToList() : new List<string>();

        /// Indicates the existence of at least one notification. If there is a notification, it is considered invalid.
        [JsonIgnore]
        public bool IsInvalid => _notifications.Any();

        /// Adds a collection of notifications
        public void AddNotifications(IReadOnlyCollection<Notification> notifications)
        {
            if (notifications != null && notifications.Any())
                _notifications.AddRange(notifications);
        }

        /// Adds a notification
        public void AddNotification(string message)
        {
            _notifications.Add(new Notification(message));
        }

        protected void NotifyValidationError<TV, TE>(TV validation, TE entity) where TV : AbstractValidator<TE> where TE : Entity
        {
            var validator = validation.Validate(entity);

            var errors = validator.Errors;

            foreach (var error in errors)
            {
                AddNotification(error.ErrorMessage);
            }
        }
    }
}
